{
  "abs()": "function abs(){return Math.abs}",
  "max()": "function max(){return Math.max}",
  "min()": "function min(){return Math.min}",
  "bind": "function _$rapyd$_bind(fn,thisArg){var ret;if(fn.orig){fn=fn.orig}if(thisArg===false){return fn}ret=function(){return fn.apply(thisArg,arguments)};ret.orig=fn;return ret}",
  "rebind_all": "function _$rapyd$_rebind_all(thisArg,rebind){if(typeof rebind===\"undefined\"){rebind=true}for(var p in thisArg){if(thisArg[p]&&thisArg[p].orig){if(rebind){thisArg[p]=_$rapyd$_bind(thisArg[p],thisArg)}else{thisArg[p]=thisArg[p].orig}}}}",
  "dir": "function dir(item){var arr;arr=[];for(var i in item){arr.push(i)}return arr}",
  "enumerate": "function enumerate(iterable){var ans,iterator;if(Array.isArray(iterable)||typeof iterable===\"string\"){ans={\"_i\":-1,\"next\":function(){this._i+=1;if(this._i<iterable.length){return{\"done\":false,\"value\":[this._i,iterable[this._i]]}}return{\"done\":true}}};ans[_$rapyd$_iterator_symbol]=function(){return this};return ans}if(typeof iterable[_$rapyd$_iterator_symbol]===\"function\"){iterator=typeof Map===\"function\"&&iterable instanceof Map?iterable.keys():iterable[_$rapyd$_iterator_symbol]();ans={\"_iterator\":iterator,\"_i\":-1,\"next\":function(){var r;r=this._iterator.next();if(r.done){return{\"done\":true}}this._i+=1;return{\"done\":false,\"value\":[this._i,r.value]}}};ans[_$rapyd$_iterator_symbol]=function(){return this};return ans}return enumerate(Object.keys(iterable))}",
  "iter": "function iter(iterable){var ans;if(Array.isArray(iterable)||typeof iterable===\"string\"){ans={\"_i\":-1,\"next\":function(){this._i+=1;if(this._i<iterable.length){return{\"done\":false,\"value\":iterable[this._i]}}return{\"done\":true}}};ans[_$rapyd$_iterator_symbol]=function(){return this};return ans}if(typeof iterable[_$rapyd$_iterator_symbol]===\"function\"){return typeof Map===\"function\"&&iterable instanceof Map?iterable.keys():iterable[_$rapyd$_iterator_symbol]()}return iter(Object.keys(iterable))}",
  "eslice": "function _$rapyd$_eslice(arr,step,start,end){var isString;arr=arr.slice(0);if(typeof arr===\"string\"||arr instanceof String){isString=true;arr=arr.split(\"\")}if(step<0){step=-step;arr.reverse();if(typeof start!==\"undefined\"){start=arr.length-start-1}if(typeof end!==\"undefined\"){end=arr.length-end-1}}if(typeof start===\"undefined\"){start=0}if(typeof end===\"undefined\"){end=arr.length}arr=arr.slice(start,end).filter(function(e,i){return i%step===0});return isString?arr.join(\"\"):arr}",
  "list": "function list(iterable){var iterator,ans,result;if(Array.isArray(iterable)){return iterable.slice()}if(typeof iterable===\"string\"){return iterable.split(\"\")}if(typeof iterable[_$rapyd$_iterator_symbol]===\"function\"){iterator=typeof Map===\"function\"&&iterable instanceof Map?iterable.keys():iterable[_$rapyd$_iterator_symbol]();ans=[];result=iterator.next();while(!result.done){ans.push(result.value);result=iterator.next()}return ans}return Object.keys(iterable)}",
  "extends": "function _$rapyd$_extends(child,parent){child.prototype=Object.create(parent.prototype);child.prototype.constructor=child}",
  "_$rapyd$_flatten": "function _$rapyd$_flatten(arr){var ans,value;ans=[];for(var i=0; i<arr.length; i++){value=arr[i];if(Array.isArray(value)){ans=ans.concat(_$rapyd$_flatten(value))}else{ans.push(value)}}return ans}",
  "_$rapyd$_in()": "function _$rapyd$_in(){if(typeof Map===\"function\"&&typeof Set===\"function\"){return function(val,arr){if(Array.isArray(arr)||typeof arr===\"string\"){return arr.indexOf(val)!==-1}if((arr instanceof Map||arr instanceof Set)){return arr.has(val)}return arr.hasOwnProperty(val)}}return function(val,arr){if(Array.isArray(arr)||typeof arr===\"string\"){return arr.indexOf(val)!==-1}return arr.hasOwnProperty(val)}}",
  "iterable": "function _$rapyd$_Iterable(iterable){var iterator,ans,result;if(Array.isArray(iterable)||typeof iterable===\"string\"){return iterable}if(typeof iterable[_$rapyd$_iterator_symbol]===\"function\"){iterator=typeof Map===\"function\"&&iterable instanceof Map?iterable.keys():iterable[_$rapyd$_iterator_symbol]();ans=[];result=iterator.next();while(!result.done){ans.push(result.value);result=iterator.next()}return ans}return Object.keys(iterable)}",
  "len()": "function _$rapyd$_len(){if(typeof Set===\"function\"&&typeof Map===\"function\"){return function(obj){if(Array.isArray(obj)||typeof obj===\"string\"){return obj.length}if(obj instanceof Set||obj instanceof Map){return obj.size}return Object.keys(obj).length}}return function(obj){if(Array.isArray(obj)||typeof obj===\"string\"){return obj.length}return Object.keys(obj).length}}",
  "mixin": "function _$rapyd$_mixin(target,source,overwrite){for(var i in source){if(source.hasOwnProperty(i)&&overwrite||typeof target[i]===\"undefined\"){target[i]=source[i]}}}",
  "print": "function _$rapyd$_print(){if(typeof console===\"object\"){console.log.apply(console,arguments)}}",
  "range": "function range(start,stop,step){var length;if(arguments.length<=1){stop=start||0;start=0}step=arguments[2]||1;length=Math.max(Math.ceil((stop-start)/step),0);return(function(){var d={};d[_$rapyd$_iterator_symbol]=function(){return this};d[\"_i\"]=start-step;d[\"_idx\"]=-1;d[\"next\"]=function(){this._i+=step;this._idx+=1;if(this._idx>=length){return{\"done\":true}}return{\"done\":false,\"value\":this._i}};return d})()}",
  "reversed": "function reversed(iterable){var ans;if(Array.isArray(iterable)||typeof iterable===\"string\"){ans={\"_i\":iterable.length,\"next\":function(){this._i-=1;if(this._i>-1){return{\"done\":false,\"value\":iterable[this._i]}}return{\"done\":true}}};ans[_$rapyd$_iterator_symbol]=function(){return this};return ans}throw TypeError(\"reversed() can only be called on arrays or strings\")}",
  "sum": "function sum(arr,start){return arr.reduce(function(prev,cur){return prev+cur},start||0)}",
  "getattr": "function getattr(obj,name,defval){var ret;try{ret=obj[name]}catch(_$rapyd$_Exception){if(_$rapyd$_Exception instanceof TypeError){if(defval===undefined){throw new AttributeError(\"The attribute \"+name+\" is not present\")}return defval}else{throw _$rapyd$_Exception}}if(ret===undefined&&!(name in obj)){if(defval===undefined){throw new AttributeError(\"The attribute \"+name+\" is not present\")}ret=defval}return ret}",
  "setattr": "function setattr(obj,name,value){obj[name]=value}",
  "hasattr": "function hasattr(obj,name){return name in obj}",
  "_$rapyd$_desugar_kwargs()": "function _$rapyd$_desugar_kwargs(){if(typeof Object.assign===\"function\"){return function(){var ans;ans={};ans[_$rapyd$_kwargs_symbol]=true;return Object.assign.apply(ans,arguments)}}return function(){var ans,keys;ans={};ans[_$rapyd$_kwargs_symbol]=true;for(var i = 0; i < arguments.length; i++){keys=Object.keys(arguments[i]);for(var j = 0; j < keys.length; j++){ans[keys[j]]=arguments[i][keys[j]]}}return ans}}",
  "#dependencies#": {
    "errors": {
      "extends": true
    }
  },
  "errors": "var Exception = Error;function AttributeError(){AttributeError.prototype.__init__.apply(this,arguments)}_$rapyd$_extends(AttributeError,Error);AttributeError.prototype.__init__=function __init__(msg){var self=this;self.message=msg;self.stack=(new Error).stack};AttributeError.prototype.name=\"AttributeError\";function IndexError(){IndexError.prototype.__init__.apply(this,arguments)}_$rapyd$_extends(IndexError,Error);IndexError.prototype.__init__=function __init__(msg){var self=this;self.message=msg;self.stack=(new Error).stack};IndexError.prototype.name=\"IndexError\";function KeyError(){KeyError.prototype.__init__.apply(this,arguments)}_$rapyd$_extends(KeyError,Error);KeyError.prototype.__init__=function __init__(msg){var self=this;self.message=msg;self.stack=(new Error).stack};KeyError.prototype.name=\"KeyError\";function ValueError(){ValueError.prototype.__init__.apply(this,arguments)}_$rapyd$_extends(ValueError,Error);ValueError.prototype.__init__=function __init__(msg){var self=this;self.message=msg;self.stack=(new Error).stack};ValueError.prototype.name=\"ValueError\""
}